# CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ for more details
#
version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.25.0
      - run:
          name: Build application Docker image
          command: |
            docker-compose -f docker-compose.yml -f docker-compose.build.yml up --build -d
      - run:
          name: Wait for Docker Image
          command: |
            while sleep 5; do docker ps -a; if [[ -n "`docker ps | grep webapp | grep ' Up '`" ]]; then break; fi; done
      - run:
          name: Run tests
          command: |
            docker-compose exec webapp /bin/bash -c "/webodm/webodm.sh test"

