version: '2'
services:
  db:
    build: ./db
    container_name: db
    ports:
        - "5432"
  webapp:
    build: .
    container_name: webapp
    entrypoint: /bin/bash -c "chmod +x /webodm/*.sh && /webodm/wait-for-it.sh db:5432 -- /webodm/start.sh"
    volumes:
      - .:/webodm
      - /webodm/nodeodm/external/node-OpenDroneMap/node_modules
      - /webodm/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure:10