# Chaining this file to the main docker-compose file adds
# a default processing node instance. This is best for users
# who are just getting started with WebODM.

version: '2.1'
services:
  webapp:
    depends_on:
      - node-odm
    environment:
      - PYOPENCL_COMPILER_OUTPUT=1
  node-odm:
    image: opendronemap/nodeodm:gpu.intel
    devices:
      - "/dev/dri"
    ports:
      - "3000"
    restart: unless-stopped
    oom_score_adj: 500
    environment:
      - PYOPENCL_COMPILER_OUTPUT=1
    deploy:
      resources:
        limits:
          cpus: 3
          memory: 6144M
        reservations:
          cpus: 2
          memory: 4096M
